import type { Day } from '../types';

const p = (text: string) => ({ type: 'p' as const, text });
const q = (text: string) => ({ type: 'quote' as const, text });

export const b2c1Day1: Day = {
  day: 1,
  slug: 'professional-identity',
  title: 'Educational Identity & Teaching Philosophy',
  theme: 'IDENTIDAD PROFESIONAL Y VISIÓN MOA',
  guidingQuestion: 'What kind of teacher am I, and what kind of teacher do I want to become?',
  schedule: '10:30 - 12:00 (90 minutes)',
  objectives: [
    'Comprender argumentos y opiniones en textos de nivel B2/C1.',
    'Identificar ideas principales, evidencias y conclusiones.',
    'Inferir significado a partir del contexto.',
    'Analizar la postura del autor.',
    'Utilizar vocabulario académico relacionado con educación y desarrollo profesional.',
    'Analizar cómo las creencias docentes influyen en la práctica educativa.',
    'Identificar elementos de una filosofía de enseñanza efectiva.',
    'Diseñar preguntas de pensamiento crítico para una lectura.',
    'Reflexionar sobre la alineación entre sus creencias y la metodología MOA.',
  ],
  reading: {
    title: 'The Teacher I Have Become: Beyond Methods and Materials',
    blocks: [
      p(`When I began teaching nearly fifteen years ago, I believed that successful teaching depended primarily on mastering methods and materials. I spent hours searching for engaging activities, designing attractive presentations, and organizing lessons with great attention to detail. If a lesson did not go well, I usually assumed that I had chosen the wrong activity or failed to explain a concept clearly enough.`),
      p(`At that stage of my career, I viewed teaching as a technical profession. I believed that effective teachers were those who possessed a large collection of strategies and knew how to apply them efficiently. Although I cared deeply about my students, I often focused more on what I was doing than on what they were actually learning.`),
      p(`Looking back, I realize that I had underestimated the importance of teaching beliefs.`),
      p(`Over the years, I have learned that every instructional decision reflects a set of assumptions about learning. Whether we realize it or not, our beliefs influence the way we plan lessons, organize activities, respond to mistakes, assess progress, and interact with students. Long before students notice our methodology, they experience the consequences of our educational philosophy.`),
      p(`One of the first beliefs I had to reconsider was the idea that teaching meant providing answers.`),
      p(`Early in my career, I felt responsible for explaining everything. If students struggled with a concept, I explained it again. If they made mistakes, I corrected them immediately. If there was silence in the classroom, I filled it with additional explanations.`),
      p(`At the time, I believed I was helping.`),
      p(`However, after several years of teaching, I began to notice a pattern. Many students performed well when I guided them step by step, but they became less confident when they needed to solve problems independently. They often waited for instructions instead of taking initiative. Some seemed more focused on avoiding mistakes than on exploring ideas.`),
      p(`This realization forced me to ask an uncomfortable question:`),
      q(`Was my teaching helping students become independent learners, or was it making them dependent on me?`),
      p(`That question changed the way I viewed my role as a teacher.`),
      p(`I started reading more about learner autonomy, student-centered learning, and the relationship between challenge and growth. I attended workshops, observed colleagues, and reflected more critically on my own practice. During that period, I discovered that effective teaching is not always about providing the right answer at the right moment. Sometimes it is about creating the conditions that allow students to find answers for themselves.`),
      p(`Since then, I have been making a conscious effort to shift from being the center of learning to becoming a facilitator of learning.`),
      p(`This transition has not always been easy.`),
      p(`Students often expect teachers to provide immediate solutions. Teachers themselves can feel uncomfortable when learning becomes messy, unpredictable, or difficult to control. Yet some of the most meaningful learning experiences I have witnessed have emerged from moments of productive struggle—moments when students were challenged to think, discuss, test ideas, and learn from mistakes.`),
      p(`My understanding of assessment has also evolved considerably.`),
      p(`Earlier in my career, I viewed assessment primarily as a way of measuring performance. I wanted to know whether students had learned the content I had taught. While assessment certainly serves that purpose, I have gradually come to see it as something much more valuable.`),
      p(`Assessment provides evidence.`),
      p(`It tells us what students understand, where misconceptions exist, and which instructional decisions may need adjustment. The most effective teachers I have worked with do not use assessment simply to assign grades. They use it to make informed decisions about future learning.`),
      p(`This perspective has transformed the questions I ask after a lesson.`),
      p(`Instead of asking, "Did I finish everything I planned?" I am more likely to ask, "What evidence do I have that students understood?"`),
      p(`Instead of asking, "Did students complete the activity?" I ask, "What did students learn from the activity?"`),
      p(`These questions have helped me focus less on teaching and more on learning.`),
      p(`Another important lesson I have learned concerns professional growth.`),
      p(`Many people assume that experience automatically leads to expertise. However, I have met teachers with twenty years of experience who continue repeating the same practices year after year, and I have met teachers with far less experience who demonstrate remarkable professional growth.`),
      p(`The difference is not simply time.`),
      p(`The difference is reflection.`),
      p(`Professional growth occurs when teachers examine their assumptions, seek feedback, analyze evidence, and remain willing to change. For several years now, I have been keeping a reflective journal after important teaching experiences. I have also been participating in professional learning communities where educators discuss challenges, share ideas, and learn from one another.`),
      p(`These practices have helped me recognize something that I did not fully understand at the beginning of my career:`),
      q(`Teaching expertise is never finished.`),
      p(`The most effective educators are often the most curious ones. They continue asking questions. They continue seeking better solutions. They continue learning.`),
      p(`This mindset is especially important for educational leaders.`),
      p(`Leadership in education is frequently associated with positions, titles, or responsibilities. While these factors matter, I have come to believe that leadership begins with influence. Teachers exercise leadership every time they model professionalism, support colleagues, advocate for students, or contribute to a culture of continuous improvement.`),
      p(`Educational leadership is not limited to directing others. It involves creating conditions that allow excellence to flourish.`),
      p(`For this reason, I no longer define teaching primarily in terms of methods or materials.`),
      p(`Methods matter.`),
      p(`Materials matter.`),
      p(`But neither of them matters as much as the beliefs that guide their use.`),
      p(`A teacher who values curiosity will create different learning experiences from a teacher who values compliance.`),
      p(`A teacher who believes mistakes are opportunities for growth will respond differently from one who views mistakes as failures.`),
      p(`A teacher who sees learning as an active process will make different instructional decisions from one who views learning as the transmission of information.`),
      p(`The longer I teach, the more convinced I become that professional identity is not something we possess. It is something we continually construct through reflection, experience, and deliberate choice.`),
      p(`I have changed significantly since my first year in the classroom.`),
      p(`I have revised assumptions that once seemed obvious.`),
      p(`I have developed new perspectives on learning.`),
      p(`I have been rethinking what effective teaching looks like.`),
      p(`And I suspect that the teacher I become five years from now will be different from the teacher I am today.`),
      p(`That possibility does not concern me.`),
      p(`It inspires me.`),
      q(`Because meaningful professional growth begins when we recognize that becoming a better teacher is not a destination—it is an ongoing journey of learning, reflection, and purposeful change.`),
    ],
  },
  readingAfterSectionId: 'b2c1_d1_part1',
  sections: [
    {
      id: 'b2c1_d1_part1',
      title: 'FASE 1 - TEACHING BELIEFS',
      minutes: 15,
      intro: 'Responder individualmente ANTES de leer: Agree / Partially Agree / Disagree. La intención no es encontrar una respuesta “correcta”, sino hacer explícitas las creencias que posteriormente podrán contrastar con el texto.',
      fields: [
        {
          type: 'table', key: 'b2c1_d1_beliefs', label: 'Teaching Beliefs Continuum',
          columns: ['Statement', 'My position', 'Why?'], minRows: 4,
          fixedFirstColumn: [
            'Students learn best when teachers explain clearly.',
            'Mistakes are essential for learning.',
            'Fluency is more important than accuracy.',
            'Students should discover language before receiving explanations.',
          ],
        },
        { type: 'ai_prompt', key: 'b2c1_d1_ai1', prompt: 'Analyze these four statements from different educational perspectives. Give one argument supporting and one argument challenging each statement.', note: 'Selecciona una afirmación cuya respuesta de IA te haya hecho reconsiderar o profundizar tu posición.' },
        { type: 'textarea', key: 'b2c1_d1_original', label: 'My original position was...', rows: 3 },
        { type: 'textarea', key: 'b2c1_d1_ai_think', label: 'The AI response made me think about...', rows: 4 },
      ],
      checkpoint: { number: 1, items: ['Las posiciones están justificadas.', 'El participante interactuó críticamente con la respuesta de IA.', 'No se limitó a aceptar la opinión generada.'] },
    },
    {
      id: 'b2c1_d1_part2', title: 'FASE 2 - CRITICAL READING', minutes: 25,
      intro: 'Leer The Teacher I Have Become: Beyond Methods and Materials. Durante la lectura, identificar claims, evidence/experiences, changes in belief y conclusions.',
      fields: [
        { type: 'textarea', key: 'b2c1_d1_claims', label: '1. CLAIMS — ¿Qué afirma el autor?', rows: 5 },
        { type: 'textarea', key: 'b2c1_d1_evidence', label: '2. EVIDENCE / EXPERIENCES — ¿Qué experiencias utiliza para apoyar sus ideas?', rows: 5 },
        { type: 'textarea', key: 'b2c1_d1_changes', label: '3. CHANGES IN BELIEF — ¿Qué creencias tenía antes y cómo cambiaron?', rows: 5 },
        { type: 'textarea', key: 'b2c1_d1_conclusions', label: '4. CONCLUSIONS — ¿A qué conclusiones llega?', rows: 5 },
        { type: 'table', key: 'b2c1_d1_belief_table', label: 'Completar:', columns: ["Author's belief", 'Experience/evidence', 'Change in thinking'], minRows: 4 },
        { type: 'textarea', key: 'b2c1_d1_main_argument', label: "What is the author's main argument about teaching expertise?", rows: 4 },
        { type: 'textarea', key: 'b2c1_d1_position_change', label: "How does the author's understanding of teaching change throughout the text?", help: 'Identifica la evolución del pensamiento del autor, no solamente información explícita.', rows: 5 },
      ],
      checkpoint: { number: 2, items: ['What evidence supports your interpretation?', 'Is that idea explicitly stated or inferred?', "How does the author's position change?", 'Which paragraph best supports your conclusion?'] },
    },
    {
      id: 'b2c1_d1_part3', title: 'FASE 3 - CRITICAL ANALYSIS WITH AI', minutes: 20,
      intro: 'Utiliza IA para contrastar tu propia interpretación, no para sustituirla.',
      fields: [
        { type: 'ai_prompt', key: 'b2c1_d1_ai2', prompt: "Analyze the author's argument in this text. Identify the author's main claim, two supporting ideas, and one possible limitation or assumption in the author's argument." },
        { type: 'textarea', key: 'b2c1_d1_ai_correct', label: '1. AI identified correctly:', rows: 3 },
        { type: 'textarea', key: 'b2c1_d1_ai_missed', label: '2. AI missed or misunderstood:', rows: 3 },
        { type: 'textarea', key: 'b2c1_d1_ai_add', label: '3. I would add:', rows: 3 },
        { type: 'textarea', key: 'b2c1_d1_decision', label: "Do you find the author's argument convincing? Why or why not?", help: 'La respuesta debe incluir al menos una referencia concreta al texto.', rows: 6 },
      ],
      checkpoint: { number: 3, items: ['Interpretación del argumento.', 'Uso de evidencia textual.', 'Capacidad para cuestionar la respuesta de IA.', 'Justificación de la opinión.'] },
    },
    {
      id: 'b2c1_d1_part4', title: 'FASE 4 - FROM READER TO TEACHER', minutes: 20,
      intro: 'Diseña una mini-secuencia de Reading basada en el texto para estudiantes B1 (Pro/Teens 5, 6, 7). Las actividades deben promover algo más que la recuperación literal de información.',
      fields: [
        { type: 'textarea', key: 'b2c1_d1_pre', label: 'Pre-reading: 1 critical-thinking question', rows: 3 },
        { type: 'textarea', key: 'b2c1_d1_while', label: 'While-reading: 2 comprehension/analysis questions', rows: 4 },
        { type: 'textarea', key: 'b2c1_d1_post', label: 'Post-reading: 1 discussion activity', rows: 4 },
        { type: 'ai_prompt', key: 'b2c1_d1_ai3', prompt: 'Design three reading questions for B1 students based on this text. The questions should progress from comprehension to interpretation to personal response.' },
        { type: 'textarea', key: 'b2c1_d1_ai_levels', label: 'Analiza las tres preguntas e identifica cuál corresponde a cada nivel.', rows: 5 },
        { type: 'textarea', key: 'b2c1_d1_modified', label: 'Modifica al menos una pregunta.', rows: 4 },
        { type: 'textarea', key: 'b2c1_d1_justification', label: 'Justifica la modificación.', rows: 4 },
      ],
    },
    {
      id: 'b2c1_d1_part5', title: 'PART 5 - PROFESSIONAL REFLECTION', minutes: 10,
      fields: [
        { type: 'textarea', key: 'b2c1_d1_reflection', label: 'What kind of teacher am I today, and what kind of teacher do I want to become?', rows: 7 },
      ],
    },
  ],
  finalChecklist: [
    'Part 1 - Teaching Beliefs: posición frente a las cuatro afirmaciones.',
    'Part 2 - Critical Reading: claims, evidence, changes in belief y conclusions.',
    'Part 3 - AI Critical Review: evaluación de la respuesta de IA.',
    'Part 4 - Reading Sequence Design: 1 pre-reading question, 2 while-reading questions, 1 post-reading activity.',
    'Part 5 - Professional Reflection.',
  ],
};
