import type { Day } from '../types';

const p = (text: string) => ({ type: 'p' as const, text });
const q = (text: string) => ({ type: 'quote' as const, text });

export const b2c1Day1: Day = {
  day: 1,
  slug: 'professional-identity',
  title: 'Educational Identity & Teaching Philosophy',
  theme: 'PROFESSIONAL IDENTITY AND MOA VISION',
  guidingQuestion: 'What kind of teacher am I, and what kind of teacher do I want to become?',
  schedule: '10:30 - 12:00 (90 minutes)',
  objectives: [
    'Understand arguments and opinions in B2/C1-level texts.',
    'Identify main ideas, evidence, and conclusions.',
    'Infer meaning from context.',
    "Analyze the author's position.",
    'Use academic vocabulary related to education and professional development.',
    'Analyze how teaching beliefs influence educational practice.',
    'Identify elements of an effective teaching philosophy.',
    'Design critical-thinking questions for a reading text.',
    'Reflect on the alignment between personal beliefs and the MOA methodology.',
  ],
  reading: {
    title: 'The Teacher I Have Become: Beyond Methods and Materials',
    blocks: [
      p(`When I began teaching nearly fifteen years ago, I believed that successful teaching depended primarily on mastering methods and materials. I spent hours searching for engaging activities, designing attractive presentations, and organizing lessons with great attention to detail. If a lesson did not go well, I usually assumed that I had chosen the wrong activity or failed to explain a concept clearly enough.`),
      p(`At that stage of my career, I viewed teaching as a technical profession. I believed that effective teachers were those who possessed a large collection of strategies and knew how to apply them efficiently. Although I cared deeply about my students, I often focused more on what I was doing than on what they were actually learning.`),
      p(`Looking back, I realize that I had underestimated the importance of teaching beliefs.`),
      p(`Over the years, I have learned that every instructional decision reflects a set of assumptions about learning. Whether we realize it or not, our beliefs influence the way we plan lessons, organize activities, respond to mistakes, assess progress, and interact with students. Long before students notice our methodology, they experience the consequences of our educational philosophy.`),
      p(`One of the first beliefs I had to reconsider was the idea that teaching meant providing answers.`),
      p(`Early in my career, I felt responsible for explaining everything. If students struggled with a concept, I explained it again. If they made mistakes, I corrected them immediately. If there was silence in the classroom, I filled it with additional explanations.`),
      p(`At the time, I believed I was helping.`),
      p(`However, after several years of teaching, I began to notice a pattern. Many students performed well when I guided them step by step, but they became less confident when they needed to solve problems independently. They often waited for instructions instead of taking initiative. Some seemed more focused on avoiding mistakes than on exploring ideas.`),
      p(`This realization forced me to ask an uncomfortable question:`),
      q(`Was my teaching helping students become independent learners, or was it making them dependent on me?`),
      p(`That question changed the way I viewed my role as a teacher.`),
      p(`I started reading more about learner autonomy, student-centered learning, and the relationship between challenge and growth. I attended workshops, observed colleagues, and reflected more critically on my own practice. During that period, I discovered that effective teaching is not always about providing the right answer at the right moment. Sometimes it is about creating the conditions that allow students to find answers for themselves.`),
      p(`Since then, I have been making a conscious effort to shift from being the center of learning to becoming a facilitator of learning.`),
      p(`This transition has not always been easy.`),
      p(`Students often expect teachers to provide immediate solutions. Teachers themselves can feel uncomfortable when learning becomes messy, unpredictable, or difficult to control. Yet some of the most meaningful learning experiences I have witnessed have emerged from moments of productive struggle—moments when students were challenged to think, discuss, test ideas, and learn from mistakes.`),
      p(`My understanding of assessment has also evolved considerably.`),
      p(`Earlier in my career, I viewed assessment primarily as a way of measuring performance. I wanted to know whether students had learned the content I had taught. While assessment certainly serves that purpose, I have gradually come to see it as something much more valuable.`),
      p(`Assessment provides evidence.`),
      p(`It tells us what students understand, where misconceptions exist, and which instructional decisions may need adjustment. The most effective teachers I have worked with do not use assessment simply to assign grades. They use it to make informed decisions about future learning.`),
      p(`This perspective has transformed the questions I ask after a lesson.`),
      p(`Instead of asking, "Did I finish everything I planned?" I am more likely to ask, "What evidence do I have that students understood?"`),
      p(`Instead of asking, "Did students complete the activity?" I ask, "What did students learn from the activity?"`),
      p(`These questions have helped me focus less on teaching and more on learning.`),
      p(`Another important lesson I have learned concerns professional growth.`),
      p(`Many people assume that experience automatically leads to expertise. However, I have met teachers with twenty years of experience who continue repeating the same practices year after year, and I have met teachers with far less experience who demonstrate remarkable professional growth.`),
      p(`The difference is not simply time.`),
      p(`The difference is reflection.`),
      p(`Professional growth occurs when teachers examine their assumptions, seek feedback, analyze evidence, and remain willing to change. For several years now, I have been keeping a reflective journal after important teaching experiences. I have also been participating in professional learning communities where educators discuss challenges, share ideas, and learn from one another.`),
      p(`These practices have helped me recognize something that I did not fully understand at the beginning of my career:`),
      q(`Teaching expertise is never finished.`),
      p(`The most effective educators are often the most curious ones. They continue asking questions. They continue seeking better solutions. They continue learning.`),
      p(`This mindset is especially important for educational leaders.`),
      p(`Leadership in education is frequently associated with positions, titles, or responsibilities. While these factors matter, I have come to believe that leadership begins with influence. Teachers exercise leadership every time they model professionalism, support colleagues, advocate for students, or contribute to a culture of continuous improvement.`),
      p(`Educational leadership is not limited to directing others. It involves creating conditions that allow excellence to flourish.`),
      p(`For this reason, I no longer define teaching primarily in terms of methods or materials.`),
      p(`Methods matter.`),
      p(`Materials matter.`),
      p(`But neither of them matters as much as the beliefs that guide their use.`),
      p(`A teacher who values curiosity will create different learning experiences from a teacher who values compliance.`),
      p(`A teacher who believes mistakes are opportunities for growth will respond differently from one who views mistakes as failures.`),
      p(`A teacher who sees learning as an active process will make different instructional decisions from one who views learning as the transmission of information.`),
      p(`The longer I teach, the more convinced I become that professional identity is not something we possess. It is something we continually construct through reflection, experience, and deliberate choice.`),
      p(`I have changed significantly since my first year in the classroom.`),
      p(`I have revised assumptions that once seemed obvious.`),
      p(`I have developed new perspectives on learning.`),
      p(`I have been rethinking what effective teaching looks like.`),
      p(`And I suspect that the teacher I become five years from now will be different from the teacher I am today.`),
      p(`That possibility does not concern me.`),
      p(`It inspires me.`),
      q(`Because meaningful professional growth begins when we recognize that becoming a better teacher is not a destination—it is an ongoing journey of learning, reflection, and purposeful change.`),
    ],
  },
  readingBeforeFieldsSectionId: 'b2c1_d1_part2',
  sections: [
    {
      id: 'b2c1_d1_part1',
      title: 'PHASE 1 - TEACHING BELIEFS',
      minutes: 15,
      intro: 'Answer individually BEFORE reading: Agree / Partially Agree / Disagree. The goal is not to find a “correct” answer, but to make your beliefs explicit so you can later compare them with the text.',
      fields: [
        {
          type: 'table', key: 'b2c1_d1_beliefs', label: 'Teaching Beliefs Continuum',
          columns: ['Statement', 'My position', 'Why?'], minRows: 4,
          selectColumns: {
            1: ['Agree', 'Partially Agree', 'Disagree'],
          },
          fixedFirstColumn: [
            'Students learn best when teachers explain clearly.',
            'Mistakes are essential for learning.',
            'Fluency is more important than accuracy.',
            'Students should discover language before receiving explanations.',
          ],
        },
        { type: 'ai_prompt', key: 'b2c1_d1_ai1', prompt: 'Analyze these four statements from different educational perspectives. Give one argument supporting and one argument challenging each statement.', note: 'Select one statement where the AI response made you reconsider or deepen your position.' },
        { type: 'textarea', key: 'b2c1_d1_original', label: 'My original position was...', rows: 3 },
        { type: 'textarea', key: 'b2c1_d1_ai_think', label: 'The AI response made me think about...', rows: 4 },
      ],
      checkpoint: { number: 1, items: ['The positions are justified.', 'The participant engaged critically with the AI response.', 'The participant did not simply accept the generated opinion.'] },
    },
    {
      id: 'b2c1_d1_part2', title: 'PHASE 2 - CRITICAL READING', minutes: 25,
      intro: 'Review the tasks below before you begin. Then read The Teacher I Have Become: Beyond Methods and Materials and return to this section to record the author’s claims, evidence/experiences, changes in belief, and conclusions.',
      fields: [
        { type: 'textarea', key: 'b2c1_d1_claims', label: '1. CLAIMS — What does the author claim?', rows: 5 },
        { type: 'textarea', key: 'b2c1_d1_evidence', label: '2. EVIDENCE / EXPERIENCES — What experiences does the author use to support the ideas?', rows: 5 },
        { type: 'textarea', key: 'b2c1_d1_changes', label: '3. CHANGES IN BELIEF — What beliefs did the author hold before, and how did they change?', rows: 5 },
        { type: 'textarea', key: 'b2c1_d1_conclusions', label: '4. CONCLUSIONS — What conclusions does the author reach?', rows: 5 },
        {
          type: 'table',
          key: 'b2c1_d1_belief_table',
          label: 'Complete the chart with four key moments from the reading. In each row, identify one belief the author expresses, the experience or evidence that shaped that belief, and explain how the author’s thinking changed, developed, or became stronger as a result.',
          columns: ["Author's belief", 'Experience/evidence', 'Change in thinking'],
          minRows: 4,
        },
        { type: 'textarea', key: 'b2c1_d1_main_argument', label: "What is the author's main argument about teaching expertise?", rows: 4 },
        { type: 'textarea', key: 'b2c1_d1_position_change', label: "How does the author's understanding of teaching change throughout the text?", help: "Identify how the author's thinking evolves, not only explicit information.", rows: 5 },
      ],
      checkpoint: { number: 2, items: ['What evidence supports your interpretation?', 'Is that idea explicitly stated or inferred?', "How does the author's position change?", 'Which paragraph best supports your conclusion?'] },
    },
    {
      id: 'b2c1_d1_part3', title: 'PHASE 3 - CRITICAL ANALYSIS WITH AI', minutes: 20,
      intro: 'Use AI to challenge and compare your own interpretation, not to replace it.',
      fields: [
        { type: 'ai_prompt', key: 'b2c1_d1_ai2', prompt: "Analyze the author's argument in this text. Identify the author's main claim, two supporting ideas, and one possible limitation or assumption in the author's argument." },
        { type: 'textarea', key: 'b2c1_d1_ai_correct', label: '1. AI identified correctly:', rows: 3 },
        { type: 'textarea', key: 'b2c1_d1_ai_missed', label: '2. AI missed or misunderstood:', rows: 3 },
        { type: 'textarea', key: 'b2c1_d1_ai_add', label: '3. I would add:', rows: 3 },
        { type: 'textarea', key: 'b2c1_d1_decision', label: "Do you find the author's argument convincing? Why or why not?", help: 'The response must include at least one specific reference to the text.', rows: 6 },
      ],
      checkpoint: { number: 3, items: ['Interpretation of the argument.', 'Use of textual evidence.', 'Ability to question the AI response.', 'Justification of the opinion.'] },
    },
    {
      id: 'b2c1_d1_part4', title: 'PHASE 4 - FROM READER TO TEACHER', minutes: 20,
      intro: 'Design a short Reading sequence based on the text for B1 students (Pro/Teens 5, 6, 7). The activities must require more than literal information retrieval.',
      fields: [
        { type: 'textarea', key: 'b2c1_d1_pre', label: 'Pre-reading: 1 critical-thinking question', rows: 3 },
        { type: 'textarea', key: 'b2c1_d1_while', label: 'While-reading: 2 comprehension/analysis questions', rows: 4 },
        { type: 'textarea', key: 'b2c1_d1_post', label: 'Post-reading: 1 discussion activity', rows: 4 },
        { type: 'ai_prompt', key: 'b2c1_d1_ai3', prompt: 'Design three reading questions for B1 students based on this text. The questions should progress from comprehension to interpretation to personal response.' },
        { type: 'textarea', key: 'b2c1_d1_ai_levels', label: 'Analyze the three questions and identify which level each one represents.', rows: 5 },
        { type: 'textarea', key: 'b2c1_d1_modified', label: 'Modify at least one question.', rows: 4 },
        { type: 'textarea', key: 'b2c1_d1_justification', label: 'Justify the modification.', rows: 4 },
      ],
    },
    {
      id: 'b2c1_d1_part5', title: 'PART 5 - PROFESSIONAL REFLECTION', minutes: 10,
      fields: [
        { type: 'textarea', key: 'b2c1_d1_reflection', label: 'What kind of teacher am I today, and what kind of teacher do I want to become?', rows: 7 },
      ],
    },
  ],
  finalChecklist: [
    'Part 1 - Teaching Beliefs: position on the four statements.',
    'Part 2 - Critical Reading: claims, evidence, changes in belief, and conclusions.',
    'Part 3 - AI Critical Review: evaluation of the AI response.',
    'Part 4 - Reading Sequence Design: 1 pre-reading question, 2 while-reading questions, 1 post-reading activity.',
    'Part 5 - Professional Reflection.',
  ],
};
