import type { Day } from '../types';

const p = (text: string) => ({ type: 'p' as const, text });
const h = (text: string) => ({ type: 'h' as const, text });
const q = (text: string) => ({ type: 'quote' as const, text });

export const b2c1Day2: Day = {
  day: 2,
  slug: 'educational-case-studies',
  title: 'Educational Case Studies: Leading Through Challenges',
  theme: 'LIDERAZGO Y RESOLUCIÓN DE PROBLEMAS',
  guidingQuestion: 'How can I make effective decisions and lead complex situations inside the classroom and my MOA community?',
  schedule: '10:30 - 12:30 (120 minutes)',
  objectives: [
    'Comprender textos narrativos y analíticos de nivel B2/C1.',
    'Identificar relaciones de causa y efecto.',
    'Analizar problemas, intervenciones y resultados.',
    'Inferir actitudes, intenciones y perspectivas.',
    'Utilizar vocabulario relacionado con liderazgo, aprendizaje y gestión educativa.',
    'Justificar opiniones y decisiones utilizando evidencia textual.',
    'Analizar situaciones complejas de aula.',
    'Distinguir entre problemas observables, posibles causas y supuestos.',
    'Identificar información adicional necesaria antes de intervenir.',
    'Evaluar diferentes alternativas de intervención.',
    'Justificar decisiones pedagógicas utilizando evidencia.',
    'Considerar las consecuencias de una decisión antes de implementarla.',
  ],
  reading: {
    title: 'Educational Case Studies: Leading Through Challenges',
    blocks: [
      h('Case 1: The Silent Classroom'),
      p(`When Laura began teaching a new B1 group, she expected lively discussions and active participation. The students were friendly, respectful, and generally completed their assignments on time. However, after the first few weeks, she noticed a recurring problem: almost nobody spoke during class discussions.`),
      p(`Whenever she asked a question, the room became silent.`),
      p(`At first, Laura assumed the students needed more time to think. She waited longer before calling on volunteers. When participation did not improve, she began asking simpler questions. She also introduced pair discussions before whole-class activities.`),
      p(`Despite these changes, the situation remained largely the same.`),
      p(`The students participated when they worked in pairs, but they rarely contributed when speaking in front of the group. Several students avoided eye contact whenever Laura asked open-ended questions.`),
      p(`Concerned about the situation, Laura decided to gather more information. During a short anonymous survey, she asked students how they felt during speaking activities.`),
      p(`The responses surprised her.`),
      p(`Many students reported that they were afraid of making mistakes in front of their classmates. Others said they needed more preparation time before speaking. A few admitted that they often had ideas but worried that their English was not good enough.`),
      p(`Looking back, Laura realized that she had been focusing on participation as a behavior rather than confidence as a cause.`),
      p(`She decided to make several adjustments. Before discussions, she provided students with key vocabulary and sentence starters. She gave them time to organize their ideas individually before asking them to share. She also began recognizing effort rather than only correct answers.`),
      p(`After several weeks, participation gradually increased.`),
      p(`The classroom was still not the most talkative group she had ever taught, but students appeared more willing to take risks and contribute.`),
      q(`Laura concluded that the problem had not been a lack of knowledge. It had been a lack of confidence.`),

      h('Case 2: The High-Achieving Student Who Stopped Trying'),
      p(`For almost two years, Daniel had been one of the strongest students in his English program. He consistently earned high grades, participated actively, and completed assignments well before deadlines.`),
      p(`Then something changed.`),
      p(`During the second term, his teacher, Carlos, noticed that Daniel's homework quality had declined significantly. He participated less frequently and seemed disengaged during class activities. His assessment results remained above average, but his performance was no longer exceptional.`),
      p(`Initially, Carlos assumed that Daniel was simply distracted by other responsibilities. However, when the pattern continued for several weeks, he decided to investigate further.`),
      p(`During a one-on-one conversation, Carlos asked Daniel how he felt about the class.`),
      p(`Daniel's answer was unexpected.`),
      q(`"I don't think I'm learning much anymore," he admitted.`),
      p(`He explained that many classroom activities felt repetitive. Because he usually finished tasks quickly, he spent much of the lesson waiting for others to catch up. Although he still respected the teacher and enjoyed English, he no longer felt challenged.`),
      p(`Carlos realized that he had been so focused on supporting struggling students that he had overlooked the needs of one of his strongest learners.`),
      p(`After reflecting on the situation, he introduced several changes. Daniel began receiving optional extension tasks that required deeper thinking and more complex language use. He was occasionally assigned leadership roles during collaborative activities, and he was encouraged to set personal learning goals beyond the course requirements.`),
      p(`The results were not immediate, but they were noticeable.`),
      p(`Over time, Daniel became more engaged and started contributing enthusiastically again.`),
      p(`The experience taught Carlos an important lesson: effective teaching involves supporting all learners, not only those who need remediation.`),
      q(`Sometimes high-performing students stop progressing because they have stopped being challenged.`),

      h('Case 3: The Group That Relied on Translation'),
      p(`María's A2 class was energetic and enthusiastic. Students enjoyed games, participated in activities, and generally maintained positive attitudes toward learning English.`),
      p(`Yet one problem continued to appear in almost every lesson.`),
      p(`Whenever students worked in pairs or small groups, Spanish quickly became the dominant language.`),
      p(`At first, María believed this was a natural part of the learning process. She understood that students sometimes needed their first language to clarify instructions or negotiate meaning. However, as weeks passed, she noticed that many learners were using Spanish even when they already knew the English expressions they needed.`),
      p(`As a result, opportunities for meaningful language practice were being lost.`),
      p(`María responded by reminding students to use English more frequently. She posted classroom language phrases on the walls and occasionally monitored conversations more closely.`),
      p(`Although these actions produced temporary improvements, students soon returned to their usual habits.`),
      p(`Frustrated, María began observing her own lessons more critically.`),
      p(`She noticed that students were often asked to complete communicative tasks without sufficient language support. They understood the activity but lacked the confidence to maintain conversations in English for extended periods.`),
      q(`In other words, the issue was not motivation. It was preparation.`),
      p(`Before subsequent speaking tasks, María began introducing useful sentence frames, vocabulary banks, and model conversations. She also established clear expectations about when English should be used and explained why productive struggle was an important part of language learning.`),
      p(`Gradually, students started relying less on translation.`),
      p(`Spanish did not disappear completely, but English became much more common during communicative activities.`),
      p(`The experience helped María understand that expectations alone rarely change behavior.`),
      q(`Students are more likely to use the target language when they feel capable of doing so.`),
      h('Discussion Question'),
      p(`Educational challenges rarely have simple solutions. In each case, the teacher initially focused on one explanation for the problem. Later, additional evidence revealed a more complex reality.`),
      q(`As educational professionals, how can we ensure that our decisions are based on evidence rather than assumptions? And when a classroom challenge emerges, what should we investigate before deciding what to do next?`),
    ],
  },
  readingAfterSectionId: 'b2c1_d2_part1',
  sections: [
    {
      id: 'b2c1_d2_part1', title: 'FASE 1 - WHAT WOULD YOU DO?', minutes: 15,
      intro: 'Responde ANTES de leer los casos. No asumas que ya conoces la causa.',
      fields: [
        { type: 'info', key: 'b2c1_d2_sit_a', title: 'Situation A', text: 'Your students rarely speak during whole-class discussions, but they participate actively in pairs.' },
        { type: 'textarea', key: 'b2c1_d2_a', label: 'Situation A — 1. What is the problem? 2. What would you do first? 3. Why?', rows: 5 },
        { type: 'info', key: 'b2c1_d2_sit_b', title: 'Situation B', text: 'One of your strongest students has suddenly become less engaged.' },
        { type: 'textarea', key: 'b2c1_d2_b', label: 'Situation B — 1. What is the problem? 2. What would you do first? 3. Why?', rows: 5 },
        { type: 'info', key: 'b2c1_d2_sit_c', title: 'Situation C', text: 'Students continue using Spanish during communicative activities.' },
        { type: 'textarea', key: 'b2c1_d2_c', label: 'Situation C — 1. What is the problem? 2. What would you do first? 3. Why?', rows: 5 },
        { type: 'ai_prompt', key: 'b2c1_d2_ai1', prompt: 'For each situation, list three possible causes. Do not recommend solutions yet.', note: 'Compara las posibilidades generadas por IA con tus propias hipótesis.' },
        { type: 'textarea', key: 'b2c1_d2_assumption', label: 'One assumption I might have made too quickly is...', rows: 4 },
      ],
      checkpoint: { number: 1, items: ['What do you actually know?', 'What are you assuming?', 'What additional information would you need?', 'Could there be another explanation?'] },
    },
    {
      id: 'b2c1_d2_part2', title: 'FASE 2 - CASE READING: FIND THE EVIDENCE', minutes: 30,
      intro: 'Lee los tres casos. Identifica el patrón común: Initial interpretation ≠ complete diagnosis.',
      fields: [
        { type: 'table', key: 'b2c1_d2_case_matrix', label: 'Durante la lectura completa la matriz:', columns: ['Case', 'Observable problem', 'Initial explanation', 'Additional evidence', 'Deeper cause'], minRows: 3, fixedFirstColumn: ['Silent Classroom', 'High-Achieving Student', 'Reliance on Translation'] },
        { type: 'table', key: 'b2c1_d2_second_reading', label: 'Segunda lectura: encuentra al menos un ejemplo de cada categoría para cada caso.', columns: ['Case', 'Problem', 'Assumption', 'Evidence', 'Cause', 'Intervention', 'Result'], minRows: 3, fixedFirstColumn: ['Silent Classroom', 'High-Achieving Student', 'Reliance on Translation'] },
      ],
      checkpoint: { number: 2, items: ['What did the teacher initially think?', 'What evidence challenged that assumption?', 'What was the deeper problem?', 'Which action was based on evidence?', 'What changed after the intervention?'] },
    },
    {
      id: 'b2c1_d2_part3', title: 'FASE 3 - COMPARATIVE CASE ANALYSIS', minutes: 25,
      fields: [
        { type: 'table', key: 'b2c1_d2_compare', label: 'Compara los tres casos:', columns: ['Element', 'Case 1', 'Case 2', 'Case 3'], minRows: 5, fixedFirstColumn: ['Initial assumption', 'Evidence collected', 'Actual need', 'Intervention', 'Result'] },
        { type: 'textarea', key: 'b2c1_d2_common', label: 'What do the three cases have in common?', rows: 4 },
        { type: 'textarea', key: 'b2c1_d2_different', label: 'What did the teachers do differently once they had more evidence?', rows: 4 },
        { type: 'textarea', key: 'b2c1_d2_biggest', label: 'Which teacher made the biggest change in their initial interpretation? Justify using specific evidence from the cases.', rows: 5 },
        { type: 'ai_prompt', key: 'b2c1_d2_ai2', prompt: 'Compare the three educational cases. Identify the common decision-making pattern and explain how each teacher moved from an initial assumption to a more evidence-based intervention.' },
        { type: 'textarea', key: 'b2c1_d2_ai_correct', label: '1. The AI identified correctly:', rows: 3 },
        { type: 'textarea', key: 'b2c1_d2_ai_over', label: '2. The AI oversimplified:', rows: 3 },
        { type: 'textarea', key: 'b2c1_d2_ai_missed', label: '3. An important point the AI missed:', rows: 3 },
      ],
      checkpoint: { number: 3, items: ["Do you agree with the AI's interpretation?", 'What evidence supports your disagreement?', 'Is the cause clearly demonstrated or simply suggested?', 'Which case is the most complex? Why?'] },
    },
    {
      id: 'b2c1_d2_part4', title: 'FASE 4 - DECISION-MAKING CHALLENGE', minutes: 30,
      intro: 'Selecciona uno de los tres casos y asume el rol del docente responsable.',
      fields: [
        { type: 'textarea', key: 'b2c1_d2_problem', label: 'STEP 1 — DEFINE THE PROBLEM: What is the actual problem?', help: 'No describas simplemente el comportamiento observable.', rows: 4 },
        { type: 'textarea', key: 'b2c1_d2_evidence', label: 'STEP 2 — IDENTIFY THE EVIDENCE: What evidence do you have?', rows: 4 },
        { type: 'textarea', key: 'b2c1_d2_missing', label: 'STEP 3 — IDENTIFY WHAT YOU STILL NEED TO KNOW: What additional information would you collect before making a decision?', rows: 4 },
        { type: 'textarea', key: 'b2c1_d2_options', label: 'STEP 4 — GENERATE OPTIONS: Proponer tres posibles interventions.', rows: 5 },
        { type: 'table', key: 'b2c1_d2_eval_options', label: 'STEP 5 — EVALUATE THE OPTIONS', columns: ['Intervention', 'Advantages', 'Risks / Limitations'], minRows: 3, fixedFirstColumn: ['Option 1', 'Option 2', 'Option 3'] },
        { type: 'textarea', key: 'b2c1_d2_decision', label: 'STEP 6 — MAKE THE DECISION: Which intervention would you implement first? I would choose this intervention because...', help: 'La justificación debe incluir evidencia del caso.', rows: 6 },
        { type: 'ai_prompt', key: 'b2c1_d2_ai3', prompt: 'I am analyzing this educational case. Here is my diagnosis and three possible interventions. Critically evaluate my reasoning. Identify possible assumptions, risks, missing information, and alternative interpretations. Do not simply agree with me.', note: 'Piensa primero y utiliza IA después para desafiar tu pensamiento.' },
      ],
      checkpoint: { number: 4, items: ['Why did you choose this intervention?', 'What evidence supports it?', 'What could go wrong?', 'What would make you change your decision?', 'What would you monitor after implementing it?'] },
    },
    {
      id: 'b2c1_d2_part5', title: 'FASE 5 - TEACHER AS CASE-WRITER', minutes: 15,
      intro: 'Transforma uno de los casos en una actividad de pensamiento crítico para tus propios estudiantes.',
      fields: [
        { type: 'textarea', key: 'b2c1_d2_analysis_q', label: '1. Analysis question — What is the main problem in this situation?', rows: 3 },
        { type: 'textarea', key: 'b2c1_d2_eval_q', label: '2. Evaluation question — Which solution is most effective? Why?', rows: 3 },
        { type: 'textarea', key: 'b2c1_d2_decision_q', label: '3. Decision-making question — What would you do if you were the teacher? Explain your decision.', rows: 4 },
        { type: 'textarea', key: 'b2c1_d2_adapt', label: 'How would you adapt these questions for a B1 student?', rows: 5 },
      ],
    },
  ],
  finalChecklist: [
    'Part 1 - Initial assumptions.',
    'Part 2 - Comparative analysis of the three cases.',
    'Part 3 - Critical evaluation of AI output.',
    'Part 4 - Individual case diagnosis: Problem → Evidence → Missing Information → Options → Decision.',
    'Part 5 - Tres preguntas para estudiantes: Analysis, Evaluation, Decision-making.',
    'Part 6 - Adaptación de las preguntas a B1.',
  ],
};
