import type { Day } from '../types';

const p = (text: string) => ({ type: 'p' as const, text });
const q = (text: string) => ({ type: 'quote' as const, text });

export const b2c1Day3: Day = {
  day: 3,
  slug: 'opinion-articles-education',
  title: 'Opinion Articles on Education',
  theme: 'DATA, DECISION MAKING, AND CRITICAL THINKING',
  guidingQuestion: 'How can I use data, evidence and critical thinking to make better academic decisions?',
  schedule: '10:30 - 12:30 (120 minutes)',
  objectives: [
    'Understand B2/C1-level argumentative texts.',
    'Identify theses, arguments, evidence, and counterarguments.',
    'Diferenciar hechos, opiniones e interpretaciones.',
    'Recognize assumptions and possible biases.',
    'Interpret academic vocabulary related to research and education.',
    'Express and justify a position using evidence.',
    'Critically analyze educational claims.',
    'Evaluate the quality and sufficiency of evidence.',
    'Recognize when a claim is overly general.',
    'Formulate questions that promote critical thinking.',
    'Connect educational research arguments with classroom decisions.',
    'Take a professional position without reducing a complex problem to an absolute answer.',
  ],
  reading: {
    title: 'Should Grammar Be Taught Explicitly? An Ongoing Debate in Language Education',
    blocks: [
      p(`Few topics generate as much discussion among language teachers as the role of grammar instruction. Walk into a professional development conference, join an online teaching forum, or observe a curriculum planning meeting, and sooner or later the question is likely to emerge:`),
      q(`Should grammar be taught explicitly, or should students discover patterns through communication and exposure to language?`),
      p(`The debate is not new. In fact, language educators have been discussing this issue for decades. Yet despite years of research and classroom experience, there is still no universal agreement.`),
      p(`Supporters of explicit grammar instruction argue that learners benefit when language structures are explained clearly and directly. According to this perspective, students should understand grammatical rules before they are expected to use them independently.`),
      p(`Advocates of this approach point to several advantages.`),
      p(`First, explicit instruction can help students notice patterns that they might otherwise overlook. English grammar contains many structures that are difficult to identify through exposure alone, particularly for learners whose first language operates differently.`),
      p(`Second, direct explanations may reduce confusion and frustration. Rather than asking students to guess how a language structure works, teachers provide a clear framework that students can apply during practice activities.`),
      p(`Research has also suggested that explicit knowledge can support accuracy, especially in academic contexts where precise language use is important.`),
      p(`For these reasons, many teachers continue to include grammar presentations as a regular part of their lessons.`),
      p(`However, critics argue that explicit instruction has important limitations.`),
      p(`They point out that knowing a rule is not the same as being able to use it effectively during real communication.`),
      p(`Most language teachers have encountered students who can correctly explain a grammatical structure on a test yet struggle to use it spontaneously in conversation. These learners may possess significant declarative knowledge—the ability to describe language—but relatively limited procedural knowledge—the ability to use language automatically and fluently.`),
      p(`From this perspective, learning occurs most effectively when students actively engage with meaningful language rather than focusing primarily on rules.`),
      p(`Supporters of more communicative approaches argue that language is a skill, not merely a body of knowledge. Just as people do not learn to play a musical instrument by studying theory alone, they do not develop communicative competence by memorizing grammatical explanations.`),
      p(`Instead, learners need opportunities to notice patterns, experiment with language, receive feedback, and gradually refine their understanding through use.`),
      p(`Advocates of this position often emphasize student-centered learning and discovery-based instruction. They argue that when learners actively construct understanding, the learning process becomes deeper and more memorable.`),
      p(`At first glance, these two perspectives appear incompatible.`),
      p(`One emphasizes explanation.`),
      p(`The other emphasizes discovery.`),
      p(`One prioritizes clarity.`),
      p(`The other prioritizes exploration.`),
      p(`Yet the reality may be more complex than the debate sometimes suggests.`),
      p(`Educational research increasingly indicates that effective teaching rarely depends on choosing one extreme position over another. Instead, successful teachers often combine elements of different approaches according to learner needs, instructional goals, and contextual factors.`),
      p(`For example, beginner learners may benefit from carefully structured explanations that reduce cognitive overload and provide clear guidance. More advanced learners, however, may gain greater benefit from tasks that encourage analysis, inference, and independent problem-solving.`),
      p(`Similarly, certain grammatical structures may be relatively easy to discover through exposure, while others may require more direct support from the teacher.`),
      q(`The effectiveness of a strategy may therefore depend less on the strategy itself and more on how, when, and why it is used.`),
      p(`This idea aligns with a broader principle in education: context matters.`),
      p(`Unfortunately, discussions about teaching methods sometimes oversimplify complex realities. Teachers may hear statements such as "Grammar should never be taught explicitly" or "Students must understand rules before practicing language."`),
      p(`Although these claims sound decisive, they often ignore important variables.`),
      p(`How old are the learners?`),
      p(`What are their proficiency levels?`),
      p(`What are their learning goals?`),
      p(`What evidence supports the effectiveness of a particular approach in that context?`),
      p(`Without considering these questions, even well-intentioned recommendations can become misleading.`),
      p(`Another challenge involves confirmation bias—the tendency to favor information that supports existing beliefs while ignoring contradictory evidence.`),
      p(`A teacher who strongly prefers explicit instruction may focus on successful examples that confirm that preference. Conversely, a teacher who values discovery learning may pay greater attention to evidence supporting student-centered approaches.`),
      p(`As a result, professional discussions sometimes become debates about personal preferences rather than analyses of evidence.`),
      p(`This raises an important question:`),
      q(`How should educators decide which approach to use?`),
      p(`One possible answer is that teaching decisions should be informed by multiple sources of evidence.`),
      p(`Research findings provide valuable insights, but they do not replace professional judgment.`),
      p(`Classroom observations provide useful information, but individual experiences may not always represent broader patterns.`),
      p(`Student performance data can reveal important trends, but numbers alone rarely tell the complete story.`),
      p(`Effective educators therefore learn to combine evidence from different sources while remaining open to revising their assumptions.`),
      p(`Perhaps the most productive question is not whether grammar should be taught explicitly or implicitly.`),
      p(`Perhaps the better question is:`),
      q(`What kind of instruction will help these students learn most effectively in this specific situation?`),
      p(`Answering that question requires more than experience.`),
      p(`It requires critical thinking, careful analysis of evidence, and a willingness to reconsider long-held beliefs.`),
      p(`And those may be among the most important skills an educator can develop.`),
    ],
  },
  readingAfterSectionId: 'b2c1_d3_part1',
  sections: [
    {
      id: 'b2c1_d3_part1',
      title: 'PHASE 1 - AGREE, DISAGREE, IT DEPENDS',
      minutes: 15,
      intro: 'Answer BEFORE reading. For each statement, indicate your position, your reason, and what information you would need before making a stronger claim. An opinion is not necessarily an evidence-based conclusion.',
      fields: [
        {
          type: 'table', key: 'b2c1_d3_initial_positions', label: 'Initial position',
          columns: ['Statement', 'My position: Agree / Disagree / It depends', 'My reason', 'What information would I need before making a stronger claim?'], minRows: 4,
          fixedFirstColumn: [
            'Students learn more when they struggle.',
            'Technology always improves learning.',
            'Grammar explanations should be brief.',
            'Assessment should focus on progress rather than grades.',
          ],
        },
        { type: 'ai_prompt', key: 'b2c1_d3_ai1', prompt: 'For each statement, identify one factor that could make the statement true and one factor that could make it false. Explain why context matters.' },
        { type: 'textarea', key: 'b2c1_d3_contextual_statement', label: 'Identify one statement you initially treated as absolute and now consider more contextual.', rows: 4 },
      ],
      checkpoint: { number: 1, items: ['Distinguishes opinion from a claim.', 'Considers contextual variables.', 'Does not automatically accept the AI response.', 'What would you need to know before deciding?', 'Is your statement always true?', 'What could change your conclusion?'] },
    },
    {
      id: 'b2c1_d3_part2',
      title: 'PHASE 2 - ARGUMENT MAPPING',
      minutes: 30,
      intro: "First reading: identify the author's general position without reducing it to “for” or “against.” Second reading: map the argument.",
      fields: [
        { type: 'textarea', key: 'b2c1_d3_overall_position', label: "What is the author's overall position?", rows: 4 },
        {
          type: 'table', key: 'b2c1_d3_argument_map', label: 'Argument map', columns: ['Element', 'Evidence from the text'], minRows: 7,
          fixedFirstColumn: ['Main question', 'Argument for explicit instruction', 'Argument against it', 'Supporting evidence', 'Counterargument', 'Contextual factors', "Author's conclusion"],
        },
        { type: 'textarea', key: 'b2c1_d3_actual_position', label: "What is the author's actual position?", help: 'Show that you recognize the contextual, non-absolute position developed in the text.', rows: 5 },
      ],
      checkpoint: { number: 2, items: ['What is the thesis?', 'Which argument supports it?', 'Where does the author introduce an alternative perspective?', 'What evidence is actually provided?', "What is the author's final position?"] },
    },
    {
      id: 'b2c1_d3_part3',
      title: 'PHASE 3 - EVIDENCE QUALITY CHECK',
      minutes: 25,
      intro: 'Select three statements from the text and classify them as FACT, INTERPRETATION, or OPINION / CLAIM. Then evaluate the evidence.',
      fields: [
        { type: 'table', key: 'b2c1_d3_claims', label: 'Claim analysis', columns: ['Claim', 'Type', 'Evidence provided', 'Is the evidence sufficient?'], minRows: 3 },
        { type: 'textarea', key: 'b2c1_d3_critical_question', label: 'Does the text provide enough evidence to prove every claim it makes?', help: 'Justify your response.', rows: 5 },
        { type: 'ai_prompt', key: 'b2c1_d3_ai2', prompt: 'Analyze the article as a critical reader. Identify three claims made by the author and evaluate whether the evidence provided is strong, moderate, weak, or insufficient. Explain your reasoning.' },
        { type: 'textarea', key: 'b2c1_d3_ai_agree', label: '1. I agree with the AI because...', rows: 3 },
        { type: 'textarea', key: 'b2c1_d3_ai_disagree', label: '2. I disagree with the AI because...', rows: 3 },
        { type: 'textarea', key: 'b2c1_d3_ai_overlooked', label: '3. The AI overlooked...', rows: 3 },
      ],
      checkpoint: { number: 3, items: ['What makes this evidence convincing?', 'Is the evidence direct or indirect?', 'Does the evidence support the claim, or merely relate to it?', 'What information is missing?', 'Could another interpretation be possible?'] },
    },
    {
      id: 'b2c1_d3_part4',
      title: 'PHASE 4 - FROM EVIDENCE TO PROFESSIONAL DECISION',
      minutes: 30,
      intro: 'Scenario: You are planning a grammar lesson for a group of students. Some students perform well in grammar exercises but struggle to use the structures spontaneously when speaking.',
      fields: [
        { type: 'textarea', key: 'b2c1_d3_problem', label: 'Step 1 — Identify the problem: What do you actually know?', rows: 4 },
        { type: 'textarea', key: 'b2c1_d3_evidence', label: 'Step 2 — Identify the evidence: What evidence do you have?', rows: 4 },
        { type: 'textarea', key: 'b2c1_d3_missing', label: 'Step 3 — Identify what is missing: What additional evidence would you need?', rows: 4 },
        { type: 'info', key: 'b2c1_d3_alternatives_info', title: 'Step 4 — Consider alternatives', text: 'A. More explicit grammar explanations.\nB. More controlled grammar practice.\nC. More meaningful communicative use.\nD. A combination of approaches.' },
        { type: 'textarea', key: 'b2c1_d3_alternatives', label: 'Which option(s) would you consider and why?', rows: 4 },
        { type: 'textarea', key: 'b2c1_d3_decision', label: 'Step 5 — Make a decision: Which approach would you choose first, and why?', help: 'Include evidence, learner needs, context, and justification.', rows: 6 },
        { type: 'ai_prompt', key: 'b2c1_d3_ai3', prompt: 'I have analyzed this teaching situation and reached the following conclusion: [insert conclusion]. Challenge my reasoning. Identify assumptions, missing evidence, alternative interpretations, and potential weaknesses in my decision.' },
        { type: 'textarea', key: 'b2c1_d3_after_ai', label: 'Did the AI critique change or strengthen your decision? Explain.', rows: 5 },
      ],
      checkpoint: { number: 4, items: ['What evidence supports your decision?', 'What assumption are you making?', 'What would make you change your decision?', 'Why did you reject the other options?', 'How would you know whether your intervention worked?'] },
    },
    {
      id: 'b2c1_d3_part5',
      title: 'PHASE 5 - DESIGNING CRITICAL READING QUESTIONS',
      minutes: 20,
      intro: 'Based on the text, design three B1 questions that require different levels of thinking.',
      fields: [
        { type: 'textarea', key: 'b2c1_d3_analysis_q', label: '1. Analysis Question', help: 'It must require the student to identify and examine information or relationships between ideas.', rows: 4 },
        { type: 'textarea', key: 'b2c1_d3_evaluation_q', label: '2. Evaluation Question', help: 'It must require a justified judgment.', rows: 4 },
        { type: 'textarea', key: 'b2c1_d3_argumentation_q', label: '3. Argumentation Question', help: 'It must require the student to support a personal position.', rows: 4 },
        { type: 'ai_prompt', key: 'b2c1_d3_ai4', prompt: 'Create three B1-level questions based on this article: one analysis question, one evaluation question, and one argumentation question. Make sure each question requires a different level of thinking.' },
        { type: 'textarea', key: 'b2c1_d3_ai_eval', label: 'Evaluate the AI questions and identify whether they really correspond to the requested cognitive level.', rows: 5 },
        { type: 'textarea', key: 'b2c1_d3_ai_modify', label: 'Modify at least one question.', rows: 4 },
        { type: 'textarea', key: 'b2c1_d3_ai_explain', label: 'Explain why you modified it.', rows: 4 },
      ],
    },
  ],
  finalChecklist: [
    'Part 1 - Initial Position: analysis of the four statements.',
    'Part 2 - Argument Map: thesis, arguments, counterarguments, evidence, conclusion.',
    'Part 3 - Evidence Quality Check: analysis of three claims.',
    'Part 4 - AI Critical Review: evaluation of the AI response.',
    'Part 5 - Professional Decision: Evidence → Missing Information → Options → Decision → Justification.',
    'Part 6 - Critical Reading Questions: Analysis, Evaluation, Argumentation.',
    'Part 7 - Adaptation: revision of the questions for B1 students.',
  ],
};
