import type { Day } from '../types';

const p = (text: string) => ({ type: 'p' as const, text });
const q = (text: string) => ({ type: 'quote' as const, text });

export const b2c1Day4: Day = {
  day: 4,
  slug: 'research-informed-teaching',
  title: 'Research-Informed Teaching',
  theme: 'FUTURE, GROWTH, AND PLANNING',
  guidingQuestion: 'How can I continue growing professionally and contribute to the academic excellence of MOA Academy?',
  schedule: '10:30 - 12:30 (120 minutes)',
  objectives: [
    'Understand B2/C1-level academic and popular-science texts.',
    'Identify main ideas, arguments, and evidence.',
    'Interpret information related to educational research.',
    'Infer implications from explicit information.',
    'Evaluate claims and recommendations in a text.',
    'Use academic vocabulary related to learning, teaching, research, and professional development.',
    'Connect educational research with real classroom situations.',
    'Distinguish between a finding, a recommendation, and a personal opinion.',
    'Evaluate whether a strategy is applicable in context.',
    'Transform a research-informed idea into a pedagogical action.',
    'Identify a personal area for professional development.',
  ],
  reading: {
    title: 'What Research Says About Effective Learning',
    blocks: [
      p(`Teachers often gain valuable insights through experience. Over time, they learn how to manage classrooms, explain difficult concepts, and respond to the needs of different learners. Experience matters, but educational research suggests that experience alone does not always lead to improvement.`),
      p(`In fact, some teachers become significantly more effective throughout their careers, while others continue using the same strategies year after year with little change in student outcomes. This observation has led many researchers to explore an important question:`),
      q(`What do highly effective teachers do differently?`),
      p(`Although educational research rarely offers simple answers, several findings have emerged consistently across different contexts and age groups. These findings do not provide a perfect formula for teaching, but they offer useful principles that can help educators make more informed decisions.`),
      p(`One of the most widely supported concepts in recent years is retrieval practice.`),
      p(`Many students believe that learning occurs primarily when they review information. As a result, they often reread notes, highlight texts, or look over materials repeatedly before an assessment.`),
      p(`While these strategies may create a feeling of familiarity, research suggests that they are not always the most effective ways to strengthen long-term memory.`),
      p(`Retrieval practice involves actively recalling information from memory rather than simply reviewing it. For example, instead of rereading vocabulary definitions, students might attempt to remember them without looking at their notes. Instead of reviewing a grammar rule, they might explain it from memory or apply it in a new context.`),
      p(`The act of retrieving information appears to strengthen learning itself.`),
      p(`This finding has important implications for classroom instruction. Short quizzes, reflection questions, exit tickets, and retrieval activities can serve not only as assessment tools but also as learning tools.`),
      p(`Another principle supported by research is spacing.`),
      p(`Many learners prefer to study intensively over a short period of time. This approach, often called cramming, can produce temporary improvements in performance. However, information learned in this way is frequently forgotten soon afterward.`),
      p(`Research suggests that learning tends to be more durable when practice is distributed across time.`),
      p(`Instead of studying a topic once and moving on permanently, students benefit from revisiting important concepts repeatedly over days, weeks, or even months. Each encounter strengthens memory and improves retention.`),
      p(`Closely related to spacing is the concept of interleaving.`),
      p(`Traditional instruction often organizes learning into isolated units. Students practice one skill repeatedly before moving to the next. Although this approach can create a sense of progress, it sometimes leads learners to rely on short-term patterns rather than genuine understanding.`),
      p(`Interleaving involves mixing different types of content or skills during practice. While this approach often feels more challenging, research suggests that it may improve long-term learning because students must continually evaluate which strategy or concept applies in each situation.`),
      p(`Interestingly, many effective learning strategies share a common characteristic:`),
      q(`They make learning feel more difficult.`),
      p(`This observation can be surprising. Both teachers and students sometimes assume that smooth performance indicates strong learning. However, psychologists have found that activities requiring greater mental effort often produce stronger and more durable learning outcomes.`),
      p(`Of course, difficulty alone does not guarantee learning. Challenges must remain productive and achievable. Excessive frustration can discourage learners and reduce motivation.`),
      p(`The goal is not to make learning harder.`),
      q(`The goal is to make thinking more active.`),
      p(`Research has also highlighted the importance of feedback.`),
      p(`Not all feedback is equally effective. Comments such as "Good job" or "Try harder" may provide encouragement, but they offer limited information about how performance can improve.`),
      p(`More effective feedback tends to be specific, actionable, and focused on learning goals. It helps learners understand what they are doing well, where improvement is needed, and what steps they can take next.`),
      p(`Importantly, feedback works best when students have opportunities to use it.`),
      p(`A detailed comment has little value if learners never revisit the task or apply the recommendation.`),
      p(`Another area receiving significant attention is student engagement.`),
      p(`Engaged students are generally more attentive, persistent, and willing to invest effort in learning. However, engagement is often misunderstood.`),
      p(`Many people associate engagement with entertainment. If students appear enthusiastic, active, or excited, they assume learning is taking place.`),
      p(`Researchers caution that engagement is more complex than visible participation.`),
      p(`Students can enjoy an activity without learning very much, just as they can experience productive learning during a demanding task that feels challenging.`),
      p(`For this reason, effective teachers look beyond participation alone. They ask whether students are thinking deeply, making connections, and applying ideas meaningfully.`),
      p(`Perhaps one of the most important findings concerns the teachers themselves.`),
      p(`Research on expertise across multiple professions suggests that improvement depends not only on experience but also on deliberate practice and reflection.`),
      p(`Highly effective professionals rarely assume that experience automatically leads to growth. Instead, they identify specific areas for improvement, seek feedback, analyze results, and make adjustments.`),
      p(`Teaching appears to follow the same pattern.`),
      p(`Reflective teachers examine evidence from their classrooms. They ask questions about student learning. They analyze successes and challenges. Most importantly, they remain willing to revise their assumptions when evidence suggests a better approach.`),
      p(`This mindset transforms professional development from an occasional event into an ongoing process.`),
      p(`Ultimately, educational research does not tell teachers exactly what to do in every situation.`),
      p(`Classrooms are complex, and no strategy works perfectly in all contexts.`),
      p(`What research can do is provide evidence that helps educators make better decisions.`),
      p(`The most effective teachers are therefore not necessarily those who know the most techniques.`),
      p(`They are often the ones who combine professional experience, critical reflection, and research-informed thinking to continually improve their practice.`),
      p(`As educators, we may never reach a point where there is nothing left to learn.`),
      p(`And perhaps that is one of the most encouraging ideas in the profession.`),
      p(`The same curiosity, persistence, and commitment to growth that we hope to inspire in our students are the qualities that allow us to keep growing as teachers ourselves.`),
    ],
  },
  readingAfterSectionId: 'b2c1_d4_part2',
  sections: [
    {
      id: 'b2c1_d4_part1',
      title: '1. PROFESSIONAL GROWTH INVENTORY',
      minutes: 15,
      intro: 'Begin individually. Then use AI to deepen one of your responses.',
      fields: [
        { type: 'textarea', key: 'b2c1_d4_do_well', label: 'What do I do well as a teacher?', rows: 4 },
        { type: 'textarea', key: 'b2c1_d4_improving', label: 'What am I currently improving?', rows: 4 },
        { type: 'textarea', key: 'b2c1_d4_need_learn', label: 'What do I still need to learn?', rows: 4 },
        { type: 'ai_prompt', key: 'b2c1_d4_ai1', prompt: 'Based on my answers, ask me three questions that could help me identify one specific area of professional growth. Do not give me solutions yet.' },
        { type: 'text', key: 'b2c1_d4_growth_area', label: 'One area I want to improve:' },
      ],
    },
    {
      id: 'b2c1_d4_part2',
      title: '2. PRE-READING — PREDICTING THE RESEARCH',
      minutes: 10,
      intro: 'Before reading, work with the title: What Research Says About Effective Learning.',
      fields: [
        { type: 'textarea', key: 'b2c1_d4_predict_argument', label: 'What do you think the text will argue?', rows: 3 },
        { type: 'textarea', key: 'b2c1_d4_predict_strategies', label: 'Which learning strategies do you expect to see?', rows: 3 },
        { type: 'textarea', key: 'b2c1_d4_current_strategies', label: 'Which strategies do you currently use?', rows: 3 },
        { type: 'textarea', key: 'b2c1_d4_strongest_evidence', label: 'Which ones do you think have the strongest evidence?', rows: 3 },
        { type: 'ai_prompt', key: 'b2c1_d4_ai2', prompt: 'Before I read the text, give me three possible claims about effective learning. Do not tell me which ones are supported by the text.' },
        { type: 'table', key: 'b2c1_d4_predictions', label: 'Prediction → Evidence from the text → Was I right?', columns: ['Prediction', 'Evidence from the text', 'Was I right?'], minRows: 3 },
      ],
    },
    {
      id: 'b2c1_d4_part3',
      title: '3. FIRST READING — UNDERSTANDING THE ARGUMENT',
      minutes: 20,
      intro: 'Read individually. The goal is not to stop at every word. Identify the main message and locate the key ideas.',
      fields: [
        { type: 'textarea', key: 'b2c1_d4_main_message', label: "What is the author's main message?", rows: 5 },
        { type: 'checkgroup', key: 'b2c1_d4_key_ideas', label: 'Ideas found in the text', options: ['Retrieval practice', 'Spacing', 'Interleaving', 'Productive difficulty', 'Feedback', 'Student engagement', 'Deliberate practice', 'Reflection'] },
        { type: 'ai_prompt', key: 'b2c1_d4_ai3', prompt: 'Explain this sentence in simpler English without changing its meaning. Then ask me one question to check if I understood it.', note: 'Use it only if you encounter a language difficulty. AI should not automatically translate the entire text.' },
      ],
      checkpoint: { number: 1, items: ['Did everyone understand the task?', 'Are participants reading and working?', 'Critical AI-use rules are being followed.'] },
    },
    {
      id: 'b2c1_d4_part4',
      title: '4. RESEARCH FINDING OR OPINION?',
      minutes: 20,
      intro: 'Classify statements taken or paraphrased from the text as Finding, Interpretation, Recommendation, or Opinion.',
      fields: [
        {
          type: 'table', key: 'b2c1_d4_classification', label: 'Classification', columns: ['Statement', 'Finding / Interpretation / Recommendation / Opinion', 'Evidence / justification'], minRows: 3,
          fixedFirstColumn: [
            'Retrieval practice involves actively recalling information from memory.',
            'Teachers should use short retrieval activities in every class.',
            'Making learning feel more difficult always produces better learning.',
          ],
        },
        { type: 'ai_prompt', key: 'b2c1_d4_ai4', prompt: 'Review my classification. Do not simply tell me the correct answers. For each answer, ask me to justify my decision using evidence from the text. Only explain the answer after I have attempted to justify it.' },
      ],
      checkpoint: { number: 2, items: ['Review the Finding / Interpretation / Recommendation / Opinion classification.', 'The participant justifies ideas with evidence from the text.', 'The AI asks for justification before explaining.'] },
    },
    {
      id: 'b2c1_d4_part5',
      title: '5. FROM RESEARCH TO CLASSROOM DECISION',
      minutes: 20,
      intro: 'Select one strategy from the text: Retrieval Practice, Spacing, Interleaving, Feedback, Deliberate Practice, or Reflection.',
      fields: [
        { type: 'text', key: 'b2c1_d4_strategy', label: 'Selected strategy' },
        {
          type: 'table', key: 'b2c1_d4_research_to_classroom', label: 'Research → Classroom decision', columns: ['Step', 'Your response'], minRows: 10,
          fixedFirstColumn: [
            '1. Research finding',
            '2. What does the text say?',
            '3. Classroom problem',
            '4. What problem could this strategy address?',
            '5. Pedagogical decision',
            '6. What would I change in my teaching?',
            '7. Implementation',
            '8. What would I actually do in a MOA class?',
            '9. Evidence of success',
            '10. How would I know whether it worked?',
          ],
        },
      ],
    },
    {
      id: 'b2c1_d4_part6',
      title: '6. AI CHALLENGE — CHALLENGE MY DECISION',
      minutes: 15,
      intro: 'AI changes roles: it will now be a critical-thinking partner. You must first select the strategy and design your application.',
      fields: [
        { type: 'ai_prompt', key: 'b2c1_d4_ai5', prompt: 'I have selected this teaching strategy and designed this classroom application. Challenge my decision. Identify three questions I should consider before implementing it. Do not rewrite my proposal for me.' },
        { type: 'textarea', key: 'b2c1_d4_three_answers', label: 'Respond to the three questions generated by the AI.', rows: 7 },
        { type: 'ai_prompt', key: 'b2c1_d4_ai6', prompt: 'Now evaluate my response. Identify one strength, one possible limitation, and one question I should investigate further.' },
      ],
      checkpoint: { number: 3, items: ['The participant is moving from research → classroom application.', 'The decision is justified.', 'AI challenges the decision instead of writing the proposal.'] },
    },
    {
      id: 'b2c1_d4_part7',
      title: '7. PROFESSIONAL GROWTH REFLECTION',
      minutes: 15,
      intro: 'Return to the opening question: What do I still need to learn?',
      fields: [
        { type: 'textarea', key: 'b2c1_d4_before', label: 'Before the reading... I believed that...', rows: 3 },
        { type: 'textarea', key: 'b2c1_d4_after', label: 'After the reading... I now think that...', rows: 3 },
        { type: 'textarea', key: 'b2c1_d4_try', label: 'One strategy I want to try...', rows: 3 },
        { type: 'textarea', key: 'b2c1_d4_prof_dev', label: 'One area of my professional development...', rows: 3 },
        { type: 'textarea', key: 'b2c1_d4_question', label: 'One question I still have...', rows: 3 },
      ],
    },
    {
      id: 'b2c1_d4_part8',
      title: '8. EVIDENCE OF THE SESSION',
      minutes: 5,
      intro: 'Final submission: Research-to-Practice Brief. Maximum one page.',
      fields: [
        { type: 'textarea', key: 'b2c1_d4_brief_finding', label: '1. Research finding — What does the text state?', rows: 4 },
        { type: 'textarea', key: 'b2c1_d4_brief_need', label: '2. Classroom need — What need could it address?', rows: 4 },
        { type: 'textarea', key: 'b2c1_d4_brief_decision', label: '3. Pedagogical decision — What would the teacher do?', rows: 4 },
        { type: 'textarea', key: 'b2c1_d4_brief_implementation', label: '4. Implementation — How would it be implemented?', rows: 4 },
        { type: 'textarea', key: 'b2c1_d4_brief_evidence', label: '5. Evidence of success — What would you observe or measure?', rows: 4 },
        { type: 'textarea', key: 'b2c1_d4_brief_reflection', label: '6. Professional reflection — What would you need to learn or improve to implement it effectively?', rows: 4 },
      ],
      checkpoint: { number: 4, items: ['Confirm that everyone is building their evidence.', 'Research-to-Practice Brief complete.', 'Professional reflection completed.', 'Active participation.'] },
    },
  ],
  finalChecklist: [
    'Research-to-Practice Brief — 1. Research finding.',
    '2. Classroom need.',
    '3. Pedagogical decision.',
    '4. Implementation.',
    '5. Evidence of success.',
    '6. Professional reflection.',
  ],
};
