import type { Day } from './types';

export const day2: Day = {
  day: 2,
  slug: 'clarity',
  title: 'Teaching with clarity',
  theme: 'CLARITY',
  guidingQuestion: 'How can I make learning clear, understandable and achievable for my students?',
  schedule: '10:30 - 12:30 (120 minutes)',
  objectives: [
    'identify the main idea and the relevant details of a text',
    'recognise a sequence of events and narrative tenses (Past Simple, Past Continuous, Past Perfect)',
    'understand vocabulary about classroom management',
    'see the difference between explaining, modelling and checking understanding',
    'make teaching decisions based on evidence',
  ],
  reading: {
    title: 'A Class That Finally Made Sense',
    blocks: [
      { type: 'p', text: 'When I first started teaching, I thought that giving clear instructions was easy. I usually explained an activity, asked my students to start, and then walked around the classroom to help them. However, I soon discovered that my students did not always understand what I wanted them to do.' },
      { type: 'p', text: 'One morning, I was teaching a speaking class. I wanted my students to work in pairs and ask each other questions about their daily routines. I explained the task and gave them a few examples. Then I asked them to begin.' },
      { type: 'p', text: 'For a few seconds, the classroom was quiet. Then everyone started asking questions. At least, that was what I thought.' },
      { type: 'p', text: 'As I walked around the room, I noticed that several students were looking at their books. One pair was discussing the questions in Spanish. Another student was waiting for her partner to tell her what to do. I stopped the activity and explained the instructions again.' },
      { type: 'p', text: 'This time, I spoke more slowly and gave more examples. I thought the problem was solved. It wasn\u2019t. A few minutes later, some students were still confused. I felt frustrated because I had explained the activity twice. I started wondering if the task itself was too difficult.' },
      { type: 'p', text: 'That afternoon, I observed another teacher\u2019s class. She was doing a similar speaking activity with her students. I paid close attention to the way she introduced the task.' },
      { type: 'p', text: 'First, she explained the objective in one simple sentence. Then she showed the students an example. Instead of only telling them what to do, she actually demonstrated the activity with another student.' },
      { type: 'p', text: 'After that, she asked the class a few simple questions to check their understanding: "What do you do first?" "Who asks the first question?" "How many questions do you ask?" The students answered, and the teacher clarified one point before they started.' },
      { type: 'p', text: 'I realized that she had not given a long explanation. She had broken the task into small steps and had shown the students what successful performance looked like.' },
      { type: 'p', text: 'The next day, I decided to try the same approach. I gave my students short instructions. Then I modeled the activity with one student. I wrote two examples on the board and asked a few questions to check that everyone understood the task.' },
      { type: 'p', text: 'This time, something was different. The students started working almost immediately. They asked fewer questions about the instructions and spent more time using English. When one student made a mistake, I was able to give feedback instead of stopping the whole activity.' },
      { type: 'p', text: 'By the end of the class, I understood something important: explaining an activity is not the same as making it clear.' },
      { type: 'p', text: 'Since then, I have changed the way I give instructions. I try to make them short and organized. I use examples when they are useful, and I model activities instead of only describing them. Most importantly, I check understanding before I ask students to work independently.' },
      { type: 'p', text: 'I still have classes where students become confused. Teaching is not always predictable. But now, when an activity does not work, I stop and ask myself a different question: What can I change to make the learning experience clearer?' },
      { type: 'quote', text: 'That small change in my thinking has made a big difference in my classroom.' },
    ],
  },
  readingAfterSectionId: 'd2_part1',
  sections: [
    {
      id: 'd2_part1',
      title: 'PART 1 - Connecting with experience',
      minutes: 15,
      intro: 'Answer BEFORE you read the text.',
      fields: [
        { type: 'textarea', key: 'd2_p1_q1', label: '1. Think about a time when your students did not understand an activity. What happened?', rows: 4 },
        { type: 'textarea', key: 'd2_p1_q2', label: '2. What were they supposed to do?', rows: 3 },
        { type: 'textarea', key: 'd2_p1_q3', label: '3. What do you think caused the confusion?', rows: 3 },
        {
          type: 'ai_prompt',
          key: 'd2_p1_ai',
          prompt: 'List five common reasons why students do not understand classroom instructions. Explain each one briefly.',
          note: 'Choose TWO reasons you agree with and explain why.',
        },
        {
          type: 'table',
          key: 'd2_p1_reasons',
          columns: ['Reason I agree with', 'Why I agree (from my own experience)'],
          minRows: 2,
          fixedFirstColumn: [],
        },
      ],
      checkpoint: {
        number: 1,
        items: ['Reflection completed.', 'Connection with real classroom experiences.', 'Critical use of AI.'],
      },
    },
    {
      id: 'd2_part2',
      title: 'PART 2 - Reading and evidence collection',
      minutes: 25,
      intro: 'Read the text and complete the tables.',
      fields: [
        {
          type: 'table',
          key: 'd2_p2_story',
          columns: ['Before the problem', 'The problem', 'What changed', 'Result'],
          minRows: 2,
        },
        {
          type: 'table',
          key: 'd2_p2_vocab',
          label: 'Vocabulary challenge',
          help: 'Choose 5 words you already know and 5 new words. Guess the meaning of the new words before you ask the AI.',
          columns: ['Word', 'Known / New', 'My guess', 'After AI: meaning + example'],
          minRows: 10,
        },
        {
          type: 'ai_prompt',
          key: 'd2_p2_ai',
          prompt: 'Explain these words using simple English suitable for A2/B1 learners. Include an example sentence.',
        },
      ],
      checkpoint: {
        number: 2,
        items: ['General understanding of the text.', 'Table completed.', 'Guesses made before using AI.'],
      },
    },
    {
      id: 'd2_part3',
      title: "PART 3 - Analysing the teacher's decision",
      minutes: 25,
      intro: 'Use evidence from the text.',
      fields: [
        {
          type: 'table',
          key: 'd2_p3_decision',
          columns: ['What the teacher originally did', 'What the teacher observed', 'What the teacher changed', 'Why the new approach worked'],
          minRows: 1,
        },
        {
          type: 'table',
          key: 'd2_p3_tenses',
          label: 'Narrative tenses discovery',
          help: 'Find examples in the text and explain why each tense is used.',
          columns: ['Tense', 'Example from the text', 'Why is it used?'],
          minRows: 6,
          fixedFirstColumn: ['Past Simple', 'Past Simple', 'Past Continuous', 'Past Continuous', 'Past Perfect', 'Past Perfect'],
        },
        {
          type: 'ai_prompt',
          key: 'd2_p3_ai',
          prompt: 'Based on the text, explain the difference between explaining an activity and making it clear.',
          note: 'Evaluate the answer and add one idea of your own taken from the text.',
        },
        { type: 'textarea', key: 'd2_p3_own', label: 'My own idea from the text', rows: 4 },
      ],
      checkpoint: {
        number: 3,
        items: ['Textual evidence used.', 'Pedagogical changes identified.', 'Active participation.'],
      },
    },
    {
      id: 'd2_part4',
      title: 'PART 4 - Professional decision-making challenge',
      minutes: 25,
      fields: [
        {
          type: 'info',
          key: 'd2_p4_case',
          title: 'THE SITUATION',
          text: 'Your students seem confused during a speaking activity. Several students are asking questions about what they should do. Others are waiting for instructions from classmates.',
        },
        { type: 'textarea', key: 'd2_p4_q1', label: '1. What evidence suggests that students do not understand?', rows: 4 },
        { type: 'textarea', key: 'd2_p4_q2', label: '2. What mistake might the teacher be making?', rows: 4 },
        { type: 'textarea', key: 'd2_p4_q3', label: '3. What would you do differently?', rows: 4 },
        {
          type: 'ai_prompt',
          key: 'd2_p4_ai',
          prompt: 'Suggest three strategies that could make classroom instructions clearer for A2/B1 learners.',
          note: 'Analyse the three proposals, choose the best one and explain why it works for your students.',
        },
        {
          type: 'table',
          key: 'd2_p4_strategy',
          columns: ['The strategy I chose', 'Why it is the best one for my classroom'],
          minRows: 1,
        },
      ],
      checkpoint: {
        number: 4,
        items: ['Decision based on evidence.', 'Clear justification.', 'Pedagogical reflection.'],
      },
    },
    {
      id: 'd2_part5',
      title: 'PART 5 - Reading as teachers',
      minutes: 20,
      intro: 'Final product. Design a reading sequence for your students, based on this text.',
      fields: [
        { type: 'textarea', key: 'd2_p5_pre', label: '1 pre-reading question', rows: 2 },
        { type: 'textarea', key: 'd2_p5_while', label: '2 while-reading questions', rows: 3 },
        { type: 'textarea', key: 'd2_p5_post', label: '1 post-reading task', rows: 3 },
        {
          type: 'ai_prompt',
          key: 'd2_p5_ai',
          prompt: 'Create three comprehension questions for A2/B1 students based on this text.',
          note: 'Evaluate the questions, select or modify the best ones and justify your changes.',
        },
        { type: 'textarea', key: 'd2_p5_changes', label: 'My changes and why I made them', rows: 5 },
      ],
    },
    {
      id: 'd2_final',
      title: 'FINAL REFLECTION',
      minutes: 10,
      fields: [
        { type: 'textarea', key: 'd2_f_apply', label: 'Three ideas I want to apply immediately', rows: 3 },
        { type: 'textarea', key: 'd2_f_avoid', label: 'Two mistakes I want to avoid', rows: 3 },
        { type: 'textarea', key: 'd2_f_change', label: 'One change I will make in my next class', rows: 3 },
      ],
    },
  ],
  finalChecklist: [
    'Part 1 - Personal experience.',
    'Part 2 - Text analysis and vocabulary.',
    'Part 3 - Narrative tenses discovery.',
    'Part 4 - Professional decision-making challenge.',
    'Part 5 - Reading sequence design.',
    'Final reflection.',
  ],
};
