import type { Day } from './types';

export const day3: Day = {
  day: 3,
  slug: 'decision',
  title: 'Teaching by making decisions',
  theme: 'DECISION',
  guidingQuestion: 'What should I do when my students are not learning?',
  schedule: '10:30 - 12:30 (120 minutes)',
  objectives: [
    'understand a simple performance report and read simple tables',
    'identify strengths and areas of concern in a group',
    'recognise patterns of error and learning needs',
    'use vocabulary about assessment and learning',
    'take relevant information from data to plan my next lessons',
  ],
  reading: {
    title: 'Understanding Student Performance',
    blocks: [
      { type: 'p', text: 'Level 4 - Midterm Performance Report. Class: Level 4. Number of students: 12. Assessment: Midterm Performance Review.' },
      { type: 'h', text: 'Overall results' },
      { type: 'p', text: 'The students have made good progress in some areas, but the results are not the same across all skills.' },
      {
        type: 'table',
        head: ['Area', 'Average result'],
        rows: [['Grammar', '85%'], ['Vocabulary', '78%'], ['Reading', '92%'], ['Speaking', '61%']],
      },
      { type: 'p', text: 'At first, the results look positive. The class has a strong reading score, and most students can understand the main ideas and important details in a text. Their grammar performance is also good. However, the speaking result is much lower than the other areas.' },
      { type: 'h', text: 'What the teacher observed' },
      { type: 'p', text: 'During speaking activities, the teacher noticed several problems. First, many students hesitate before answering questions. They often take a long time to begin speaking, even when they know the vocabulary they need.' },
      { type: 'p', text: 'Second, students frequently use Spanish when they are working with a partner. Some students begin an activity in English but change to Spanish when they have difficulty expressing an idea.' },
      { type: 'p', text: 'The teacher also noticed that students often give very short answers. Instead of saying, "I went to the park with my friends because it was my birthday," a student might simply say, "Park. With my friends."' },
      { type: 'p', text: 'These problems do not appear in every student. Some students speak confidently and use complete sentences, while others need more support.' },
      { type: 'h', text: 'Student comments' },
      { type: 'p', text: 'At the end of the assessment, the teacher asked students how they felt about speaking English. Several students said that they understood the questions but were afraid of making mistakes. One student said, "I know what I want to say, but I don\u2019t know how to say it." Another student explained, "When I speak English, I think too much about grammar." A third student said, "I need more time to practice speaking."' },
      { type: 'h', text: 'Looking at the evidence' },
      { type: 'p', text: 'The teacher compared the assessment results with the classroom observations. The reading score was 92%, so students generally understand written English well. Their grammar score was 85%, which suggests that they have learned many of the structures taught in class. Vocabulary was slightly lower at 78%, but it was still stronger than speaking.' },
      { type: 'p', text: 'The teacher therefore decided that the main problem was not simply a lack of grammar knowledge. The students needed more opportunities to use what they already knew when communicating.' },
      { type: 'h', text: 'The next step' },
      { type: 'p', text: 'Before planning the next unit, the teacher decided not to add more grammar exercises immediately. Instead, she planned to include more short speaking activities. Students would first work with useful vocabulary and sentence frames. Then they would practise with a partner before speaking in front of the whole class. The teacher would also give them time to prepare their ideas before asking them to speak.' },
      { type: 'p', text: 'The goal was not simply to make students speak more. The goal was to help them speak with greater confidence, use complete sentences, and gradually depend less on Spanish.' },
      { type: 'p', text: 'The teacher understood that the numbers alone did not explain the whole situation. The most useful information appeared when she combined results, classroom observations and student comments.' },
      { type: 'quote', text: 'Good teaching decisions begin with good questions: What is happening? What evidence do I have? What does the evidence tell me? What should I do next?' },
    ],
  },
  sections: [
    {
      id: 'd3_part1',
      title: 'PART 1 - What counts as evidence?',
      minutes: 15,
      intro: 'Answer BEFORE you read the report.',
      fields: [
        { type: 'textarea', key: 'd3_p1_q1', label: '1. How do you know if your students are learning?', rows: 4 },
        { type: 'textarea', key: 'd3_p1_q2', label: '2. What information do you usually use?', rows: 3 },
        { type: 'textarea', key: 'd3_p1_q3', label: '3. What information do you sometimes ignore?', rows: 3 },
        {
          type: 'ai_prompt',
          key: 'd3_p1_ai',
          prompt: 'List five types of evidence teachers can use to evaluate student learning. Explain how each one helps decision-making.',
          note: 'Compare the list with your own answers.',
        },
        { type: 'textarea', key: 'd3_p1_rare', label: 'One source of evidence I rarely use is...', rows: 3 },
      ],
      checkpoint: {
        number: 1,
        items: ['Reflection completed.', 'Appropriate use of AI.', 'Connection with real experience.'],
      },
    },
    {
      id: 'd3_part2',
      title: 'PART 2 - Reading and evidence collection',
      minutes: 25,
      intro: 'Read the full report.',
      fields: [
        {
          type: 'table',
          key: 'd3_p2_areas',
          columns: ['Area', 'Result', 'Strength or concern?', 'Why?'],
          minRows: 4,
          fixedFirstColumn: ['Grammar', 'Vocabulary', 'Reading', 'Speaking'],
        },
        {
          type: 'table',
          key: 'd3_p2_evidence',
          label: 'Identify the evidence',
          help: 'Write one or two examples of each type of evidence from the report.',
          columns: ['Type of evidence', 'Examples from the report'],
          minRows: 3,
          fixedFirstColumn: ['Assessment results', 'Classroom observations', 'Student comments'],
        },
        {
          type: 'ai_prompt',
          key: 'd3_p2_ai',
          prompt: 'Explain this performance report using simple English suitable for A2/B1 teachers.',
          note: 'Check carefully: does the explanation reflect the information of the text correctly?',
        },
        { type: 'textarea', key: 'd3_p2_aicheck', label: 'What the AI got wrong or left out', rows: 4 },
      ],
      checkpoint: {
        number: 2,
        items: ['General understanding.', 'Evidence identified correctly.', 'Results interpreted appropriately.'],
      },
    },
    {
      id: 'd3_part3',
      title: 'PART 3 - What does the evidence tell us?',
      minutes: 25,
      fields: [
        {
          type: 'table',
          key: 'd3_p3_meaning',
          columns: ['Evidence', 'What does it tell us?'],
          minRows: 5,
          fixedFirstColumn: [
            'Speaking score 61%',
            'Students hesitate before answering',
            'Students use Spanish',
            'Reading score 92%',
            'Students fear making mistakes',
          ],
        },
        {
          type: 'textarea',
          key: 'd3_p3_key',
          label: 'KEY QUESTION: Is the main problem grammar, confidence, vocabulary, speaking practice, or something else?',
          help: 'Justify your answer with evidence from the text.',
          rows: 6,
        },
        {
          type: 'ai_prompt',
          key: 'd3_p3_ai',
          prompt: 'Based on the evidence presented, what do you think is the most important learning need? Explain your reasoning.',
          note: 'Identify one thing you agree with and one thing you would change.',
        },
        {
          type: 'table',
          key: 'd3_p3_agree',
          columns: ['I agree with...', 'I would change...'],
          minRows: 1,
        },
      ],
      checkpoint: {
        number: 3,
        items: ['Use of textual evidence.', 'Clear justification.', 'Critical thinking about the AI answer.'],
      },
    },
    {
      id: 'd3_part4',
      title: 'PART 4 - Pedagogical decision challenge',
      minutes: 30,
      intro: 'You are the teacher of this group. You must decide what to do during the next two weeks. Analyse the options.',
      fields: [
        {
          type: 'table',
          key: 'd3_p4_options',
          columns: ['Option / Action', 'Advantages', 'Risks'],
          minRows: 4,
          fixedFirstColumn: [
            'A. Add more grammar exercises.',
            'B. Increase short speaking activities with support.',
            'C. Assign more reading tasks.',
            'D. Carry out additional assessments.',
          ],
        },
        { type: 'textarea', key: 'd3_p4_choice', label: '1. Which option would you choose?', rows: 2 },
        { type: 'textarea', key: 'd3_p4_why', label: '2. Why?', rows: 4 },
        { type: 'textarea', key: 'd3_p4_evidence', label: '3. What evidence supports your decision?', rows: 4 },
        {
          type: 'ai_prompt',
          key: 'd3_p4_ai',
          prompt: 'Suggest three classroom interventions that could help these students improve their speaking confidence.',
          note: 'Analyse the three proposals, select the most realistic one for MOA and justify your choice.',
        },
        {
          type: 'table',
          key: 'd3_p4_intervention',
          columns: ['The intervention I selected', 'Why it is realistic at MOA'],
          minRows: 1,
        },
      ],
      checkpoint: {
        number: 4,
        items: ['Decision based on evidence.', 'Clear justification.', 'Connection with the real classroom context.'],
      },
    },
    {
      id: 'd3_part5',
      title: 'PART 5 - Mini pedagogical diagnosis',
      minutes: 15,
      intro: 'Final product.',
      fields: [
        { type: 'textarea', key: 'd3_p5_problem', label: 'PROBLEM - What is the main learning problem?', rows: 3 },
        { type: 'textarea', key: 'd3_p5_evidence', label: 'EVIDENCE - What evidence supports that conclusion?', rows: 4 },
        { type: 'textarea', key: 'd3_p5_solution', label: 'POSSIBLE SOLUTION - What action would you take first?', rows: 3 },
        { type: 'textarea', key: 'd3_p5_result', label: 'EXPECTED RESULT - What would you expect to see after that action?', rows: 3 },
      ],
    },
    {
      id: 'd3_final',
      title: 'FINAL REFLECTION',
      minutes: 10,
      fields: [
        { type: 'textarea', key: 'd3_f_idea', label: 'One idea that changed my thinking', rows: 3 },
        { type: 'textarea', key: 'd3_f_overlook', label: 'One piece of evidence I usually overlook', rows: 3 },
        { type: 'textarea', key: 'd3_f_decision', label: 'One decision I would make differently after reading this report', rows: 3 },
      ],
    },
  ],
  finalChecklist: [
    'Part 1 - Reflection about evidence.',
    'Part 2 - Analysis of the report.',
    'Part 3 - Interpretation of the data.',
    'Part 4 - Pedagogical decision challenge.',
    'Part 5 - Mini pedagogical diagnosis.',
    'Final reflection.',
  ],
};
