import type { Day } from './types';

export const day4: Day = {
  day: 4,
  slug: 'growth',
  title: 'Growing as a professional',
  theme: 'GROWTH',
  guidingQuestion: 'How can I continue growing as a teacher and show what I have learned?',
  schedule: '10:30 - 12:30 (120 minutes)',
  objectives: [
    'identify main and secondary ideas and professional recommendations',
    'use vocabulary about professional development',
    'evaluate my own strengths and areas of growth',
    'choose one concrete priority for my development',
    'write one realistic professional action based on this camp',
  ],
  reading: {
    title: 'Lifelong Learning for Teachers',
    blocks: [
      { type: 'p', text: 'When people think about becoming a teacher, they often think about the first steps: studying, getting a degree, learning how to plan a lesson, and standing in front of a class for the first time. However, becoming a teacher does not end when a person gets a qualification. In many ways, that is when the real learning begins.' },
      { type: 'p', text: 'Teaching changes constantly. Students have different needs, new technologies appear, and teachers discover that the strategies that worked with one group do not always work with another. For this reason, effective teachers continue learning throughout their careers.' },
      { type: 'p', text: 'One important part of professional growth is continuous training. Teachers can attend workshops, take courses, read professional materials, or learn new teaching techniques. Training can introduce new ideas, but learning is more valuable when teachers think about how those ideas can improve their own classrooms.' },
      { type: 'p', text: 'Another useful habit is professional reflection. After a class, a teacher can ask simple questions: What worked well? What did my students find difficult? Did they achieve the objective? What could I change next time?' },
      { type: 'p', text: 'Reflection does not mean focusing only on mistakes. It means looking carefully at what happened and using that information to make better decisions.' },
      { type: 'p', text: 'Teachers can also learn by observing other teachers. When we watch a colleague teach, we may notice different ways of giving instructions, asking questions, managing activities, or helping students participate. Observation can give us ideas that we can later adapt to our own teaching style.' },
      { type: 'p', text: 'However, observation becomes more useful when it is followed by feedback. A colleague may notice something that we cannot see ourselves. For example, a teacher may believe that instructions are clear, but another teacher may notice that students need more modeling or examples.' },
      { type: 'p', text: 'Feedback can sometimes be difficult to receive. Nobody likes hearing that something in their class did not work well. However, professional teachers understand that feedback is not a personal attack. It is information that can help them improve.' },
      { type: 'p', text: 'Another powerful opportunity for growth is a community of learning. Teachers do not have to learn alone. They can share experiences, discuss classroom problems, exchange materials, and support one another. A difficult classroom situation can become a learning opportunity when teachers discuss it together.' },
      { type: 'p', text: 'Professional growth is not always easy. Teachers have busy schedules, different responsibilities, and sometimes limited time for training. It can also be difficult to change a habit that has been part of our teaching for many years.' },
      { type: 'p', text: 'This is why professional development needs to be intentional. A teacher can choose one specific area to improve instead of trying to change everything at once.' },
      { type: 'p', text: 'For example, a teacher might decide to improve classroom instructions. Another might focus on giving better feedback. Someone else might work on creating more opportunities for students to speak. Small improvements can become significant changes over time.' },
      { type: 'p', text: 'A teacher\u2019s career is therefore not a straight path from beginner to expert. It is a continuous process of learning, practising, reflecting, receiving feedback, and trying again.' },
      { type: 'p', text: 'After five years, a teacher should not simply have five years of experience. Ideally, they should have five years of learning from experience.' },
      { type: 'quote', text: 'And after ten years, the question should not only be "How long have I been teaching?" A better question is: "How have I grown as a teacher, and what am I ready to learn next?"' },
    ],
  },
  readingAfterSectionId: 'd4_part1',
  sections: [
    {
      id: 'd4_part1',
      title: 'PART 1 - Where am I as a professional?',
      minutes: 15,
      intro: 'Answer BEFORE you read the text.',
      fields: [
        { type: 'textarea', key: 'd4_p1_q1', label: '1. What makes a great teacher after five years?', rows: 3 },
        { type: 'textarea', key: 'd4_p1_q2', label: '2. What makes a great teacher after ten years?', rows: 3 },
        { type: 'textarea', key: 'd4_p1_improved', label: 'One thing I have improved as a teacher is...', rows: 3 },
        { type: 'textarea', key: 'd4_p1_needs', label: 'One thing I still need to improve is...', rows: 3 },
        {
          type: 'ai_prompt',
          key: 'd4_p1_ai',
          prompt: 'What are five important areas of professional growth for an English teacher? Explain each one briefly.',
          note: 'Compare the AI answer with your own perception.',
        },
        {
          type: 'table',
          key: 'd4_p1_table',
          columns: ['One idea that matches my answer', 'One idea I had not considered'],
          minRows: 1,
        },
      ],
      checkpoint: {
        number: 1,
        items: ['Reflection completed.', 'A personal connection was made.', 'The participant did not only copy the AI answer.'],
      },
    },
    {
      id: 'd4_part2',
      title: 'PART 2 - Reading and professional growth',
      minutes: 25,
      intro: 'Read the text and complete the table.',
      fields: [
        {
          type: 'table',
          key: 'd4_p2_practices',
          columns: ['Professional practice', 'How can it help teachers grow?'],
          minRows: 5,
          fixedFirstColumn: ['Continuous training', 'Reflection', 'Observation', 'Feedback', 'Community of learning'],
        },
        {
          type: 'textarea',
          key: 'd4_p2_challenge',
          label: 'Challenges mentioned in the text: busy schedules | limited time | resistance to change | changing old habits',
          help: 'Which of these challenges is the biggest one for you? Why?',
          rows: 4,
        },
        {
          type: 'table',
          key: 'd4_p2_vocab',
          label: 'Vocabulary challenge',
          help: 'Choose five words or expressions about professional development. Write your own idea first.',
          columns: ['Word / expression', 'What I think it means', 'Simple explanation'],
          minRows: 5,
        },
        {
          type: 'ai_prompt',
          key: 'd4_p2_ai',
          prompt: 'Explain these words and expressions using simple English suitable for an A2/B1 learner.',
        },
      ],
      checkpoint: {
        number: 2,
        items: ['Understanding of the text.', 'Professional practices identified.', 'Able to explain their meaning.'],
      },
    },
    {
      id: 'd4_part3',
      title: 'PART 3 - From reading to self-assessment',
      minutes: 25,
      intro: 'Now you analyse yourself, not the teacher of the text.',
      fields: [
        {
          type: 'matrix',
          key: 'd4_p3_selfassessment',
          label: 'Mark one column for each practice.',
          rows: ['Continuous training', 'Reflection', 'Observation', 'Feedback', 'Community of learning'],
          options: ['I already do this', 'I sometimes do this', 'I need to develop this'],
        },
        { type: 'textarea', key: 'd4_p3_strongest', label: '1. Which area is currently my strongest?', rows: 2 },
        { type: 'textarea', key: 'd4_p3_attention', label: '2. Which area needs the most attention?', rows: 2 },
        { type: 'textarea', key: 'd4_p3_evidence', label: '3. What evidence supports my answer?', rows: 4 },
        {
          type: 'ai_prompt',
          key: 'd4_p3_ai',
          prompt: 'Based on my self-assessment, suggest three practical ways I could improve in my weakest area as an English teacher.',
          note: 'You do not have to accept the recommendations automatically.',
        },
        { type: 'textarea', key: 'd4_p3_realistic', label: 'Choose one: Why is this recommendation realistic for me?', rows: 4 },
      ],
      checkpoint: {
        number: 3,
        items: ['The area was chosen with evidence.', 'The AI recommendation was evaluated, not copied.', 'The participant explained what he or she would change.'],
      },
    },
    {
      id: 'd4_part4',
      title: 'PART 4 - My professional growth decision',
      minutes: 30,
      intro: 'The central activity of the lab. Choose ONE priority area only: giving clearer instructions, classroom management, feedback, speaking activities, lesson planning, student engagement, assessment or professional reflection.',
      fields: [
        { type: 'textarea', key: 'd4_p4_priority', label: 'My priority: I want to improve...', rows: 2 },
        { type: 'textarea', key: 'd4_p4_why', label: 'Why? This is important because...', rows: 3 },
        { type: 'textarea', key: 'd4_p4_evidence', label: 'Evidence: I have noticed that...', rows: 3 },
        { type: 'textarea', key: 'd4_p4_action', label: 'My first action: I will...', rows: 3 },
        { type: 'textarea', key: 'd4_p4_when', label: 'When? I will start...', rows: 2 },
        { type: 'textarea', key: 'd4_p4_measure', label: 'How will I know I am improving? I will know because...', rows: 3 },
        {
          type: 'ai_prompt',
          key: 'd4_p4_ai',
          prompt: 'Help me turn this professional development goal into one specific, realistic and measurable action that I can implement in my teaching.',
          note: 'Review the proposal and decide if it is really specific, realistic, applicable and observable.',
        },
        {
          type: 'checkgroup',
          key: 'd4_p4_quality',
          label: 'Is my goal concrete enough?',
          options: ['specific', 'realistic', 'applicable', 'observable'],
        },
        {
          type: 'info',
          key: 'd4_p4_examples',
          title: 'Reference',
          text: 'TOO GENERAL: "I want to be a better teacher." / "I want to improve my teaching."  ///  CONCRETE: "I will give shorter instructions and model one activity before students begin independent work."',
        },
      ],
      checkpoint: {
        number: 4,
        items: ['The goal is concrete, not a list of wishes.', 'The goal is measurable and realistic.', 'The decision is connected with the evidence.'],
      },
    },
    {
      id: 'd4_part5',
      title: 'PART 5 - Final professional reflection',
      minutes: 15,
      fields: [
        { type: 'textarea', key: 'd4_p5_before', label: 'Before this camp, I...', rows: 3 },
        { type: 'textarea', key: 'd4_p5_during', label: 'During this camp, I...', rows: 3 },
        { type: 'textarea', key: 'd4_p5_now', label: 'Now I understand that...', rows: 3 },
        { type: 'textarea', key: 'd4_p5_next', label: 'My next professional challenge is...', rows: 3 },
        { type: 'textarea', key: 'd4_p5_sentence', label: 'Complete the sentence: A professional teacher never stops...', rows: 2 },
      ],
    },
    {
      id: 'd4_summit',
      title: 'MY FOUR-DAY JOURNEY - ONE MOA SUMMIT showcase',
      minutes: 15,
      intro: 'Use your notes from the four labs to prepare a short presentation about your professional growth.',
      fields: [
        { type: 'textarea', key: 'd4_summit_learned', label: 'The most important thing I learned in this camp is...', rows: 3 },
        { type: 'textarea', key: 'd4_summit_share', label: 'One thing I will share with my colleagues is...', rows: 3 },
        { type: 'textarea', key: 'd4_summit_commitment', label: 'My professional commitment for this term is...', rows: 3 },
      ],
    },
  ],
  finalChecklist: [
    'Part 1 - Initial reflection.',
    'Part 2 - Analysis of professional growth practices.',
    'Part 3 - Self-assessment.',
    'Part 4 - Priority area and Professional Growth Decision.',
    'Part 5 - Final reflection.',
    'MOA Summit showcase.',
  ],
};
